import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';

// Predefined fill colors for each section
const sectionColors = [
  'rgba(233, 118, 43, 0.5)',
  'rgba(76, 175, 80, 0.5)',
  'rgba(33, 150, 243, 0.5)',
  'rgba(156, 39, 176, 0.5)',
  'rgba(255, 235, 59, 0.5)',
  'rgba(0, 188, 212, 0.5)',
  'rgba(255, 87, 34, 0.5)',
  'rgba(121, 85, 72, 0.5)',
  'rgba(63, 81, 181, 0.5)',
  'rgba(139, 195, 74, 0.5)'
];

/**
 * MapSections
 * 
 * Displays a list of random points (markers) generated by BoundaryMap,
 * each in a styled card with section color, coordinates, and observation status.
 *
 * Props:
 *  - markers: Array<{ latitude: number, longitude: number, segment: number, status?: string }>
 */
const MapSections = ({ markers = [] }) => {
  if (!markers.length) {
    return (
      <View style={styles.emptyContainer}>
        <Text style={styles.emptyText}>No section markers to display.</Text>
      </View>
    );
  }

  return (
    <ScrollView contentContainerStyle={styles.container}>
      {markers.map((m, idx) => {
        const color = sectionColors[(m.segment - 1) % sectionColors.length];
        const status = m.status || 'Nil';
        return (
          <View key={idx} style={styles.card}>
            <View style={[styles.colorBox, { backgroundColor: color }]} />
            <View style={styles.textContainer}>
              <Text style={styles.sectionText}>
                Section {m.segment}: lat {m.latitude.toFixed(5)}, lon {m.longitude.toFixed(5)}
              </Text>
              <Text style={styles.statusText}>
                Observation status: {status}
              </Text>
            </View>
          </View>
        );
      })}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 16
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16
  },
  emptyText: {
    fontSize: 16,
    color: '#666'
  },
  card: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    elevation: 2
  },
  colorBox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    marginTop: 4,
    marginRight: 12
  },
  textContainer: {
    flex: 1
  },
  sectionText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#333'
  },
  statusText: {
    fontSize: 14,
    color: '#555'
  }
});

export default MapSections;
